#!/bin/sh
# 특정 단어가 들어간 모든 라인 일괄 삭제 스크립트

BEFORE=$1

if [ -z "${BEFORE}" ]
then
 echo Type the word to remove line
 exit 0
fi


grep -rlI --exclude='tags' --exclude='cscope.out' --exclude='.depend' --exclude='*.html' --exclude-dir='*.svn' "${BEFORE}" . | xargs sed -i "/${BEFORE}/d"

